name: Lua Language Server Diagnostics
on:
  pull_request: ~
  push:
    branches:
      - '*'

jobs:
  luals-check:
    strategy:
      matrix:
        neovim: ["0.10"]
        lua: ["5.1", "luajit-master"]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - uses: luarocks/gh-actions-lua@v10
      with:
        luaVersion: ${{matrix.lua}}

    - name: Install tools
      uses: jdx/mise-action@v2
      with:
        install_args: "neovim"

    - name: Run lua-language-server check
      run: |
        mise use neovim
        NEOTREE_LUARC=".github/workflows/.luarc-${{ matrix.lua }}.json" mise run luals-check

    - name: Run emmylua_check
      continue-on-error: true # Doesn't type-check well enough to be worth erroring on, but this runs so fast we might as well help test this out.
      run: |
        NEOTREE_LUARC=".github/workflows/.luarc-${{ matrix.lua }}.json" mise run emmylua-check
